name: Hammer City Cycle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#eb1c24'
    - '#6f6f6f'
    - '#dfdfdf'
  brandStrength: 0.4554618301335722
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
