name: Hammer City Cycle
favicon: null
layout_spectrum: 0.9841759980190545
typography_spectrum: 0.22978007420897484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4554618301335722
  lightness: 0.00900881877169013
  saturation: 0.49368200870230794
  rhythmicContrast: 0.19209099747240543
purpose: []
